"""Public package surface for document-parser."""

from document_parser.__about__ import __version__
from document_parser.adapters import AdapterRegistry, DocumentAdapter
from document_parser.exceptions import (
    AdapterExecutionError,
    AdapterNotAvailableError,
    DocumentParserError,
    ErrorCode,
    InvalidDocumentError,
    SourceNotFoundError,
    SourceReadError,
    SourceTooLargeError,
    UnsafeDocumentError,
    UnsupportedFormatError,
)
from document_parser.markdown import FormulaMode, MarkdownOptions, TableMode, to_markdown
from document_parser.models import (
    SCHEMA_VERSION,
    AssetRef,
    BoundingBox,
    ContainerBlock,
    ContainerRole,
    ContentBlock,
    CoordinateUnit,
    Diagnostic,
    DiagnosticSeverity,
    Document,
    DocumentFormat,
    DocumentMetadata,
    DocumentStatus,
    FigureBlock,
    HeadingBlock,
    ListBlock,
    ListItem,
    ListKind,
    PageBreakBlock,
    ParagraphBlock,
    SourceInfo,
    SourceLocation,
    TableBlock,
    TableCell,
    TableRow,
    TextSpan,
)
from document_parser.parser import DocumentParser, convert, inspect_source, parse
from document_parser.results import AdapterOutput, AssetPayload, ConversionResult
from document_parser.sources import (
    AdapterInput,
    DocxOptions,
    ParseOptions,
    PdfOptions,
    SourceInput,
    XlsxOptions,
)

__all__ = [
    "SCHEMA_VERSION",
    "AdapterExecutionError",
    "AdapterInput",
    "AdapterNotAvailableError",
    "AdapterOutput",
    "AdapterRegistry",
    "AssetPayload",
    "AssetRef",
    "BoundingBox",
    "ContainerBlock",
    "ContainerRole",
    "ContentBlock",
    "ConversionResult",
    "CoordinateUnit",
    "Diagnostic",
    "DiagnosticSeverity",
    "Document",
    "DocumentAdapter",
    "DocumentFormat",
    "DocumentMetadata",
    "DocumentParser",
    "DocumentParserError",
    "DocumentStatus",
    "DocxOptions",
    "ErrorCode",
    "FigureBlock",
    "FormulaMode",
    "HeadingBlock",
    "InvalidDocumentError",
    "ListBlock",
    "ListItem",
    "ListKind",
    "MarkdownOptions",
    "PageBreakBlock",
    "ParagraphBlock",
    "ParseOptions",
    "PdfOptions",
    "SourceInfo",
    "SourceInput",
    "SourceLocation",
    "SourceNotFoundError",
    "SourceReadError",
    "SourceTooLargeError",
    "TableBlock",
    "TableCell",
    "TableMode",
    "TableRow",
    "TextSpan",
    "UnsafeDocumentError",
    "UnsupportedFormatError",
    "XlsxOptions",
    "__version__",
    "convert",
    "inspect_source",
    "parse",
    "to_markdown",
]
